Description: This template creates AWS resources needed to run nginx instances for an environment

Transform: AWS::LanguageExtensions

Parameters:
  Name:
    Description: The name of the environment to create
    Type: String
    AllowedPattern: '[a-z]{3,}'
  NetworkCIDR:
    Description: The CIDR block for the environment's VPC
    Type: String
    AllowedPattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$'
  MinInstances:
    Description: Minimum number of nginx instances to run
    Type: Number
    MinValue: 1
    Default: 1
  MaxInstances:
    Description: Maximum number of nginx instances to run
    Type: Number
    MinValue: 1
    Default: 1

Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://devopspro-beyond-2.s3.eu-west-1.amazonaws.com/cloudformation/templates/example-nested-stacks-network.yaml
      Parameters:
        Name:
          Ref: Name
        NetworkCIDR:
          Ref: NetworkCIDR
  Nginx:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://devopspro-beyond-2.s3.eu-west-1.amazonaws.com/cloudformation/templates/example-nested-stacks-nginx.yaml
      Parameters:
        Environment:
          Ref: Name
        VpcId:
          Fn::GetAtt:
          - Network
          - Outputs.VpcId
        SubnetIds:
          Fn::Join:
          - ','
          - - Fn::GetAtt:
              - Network
              - Outputs.SubnetIDPrivatea
            - Fn::GetAtt:
              - Network
              - Outputs.SubnetIDPrivateb
            - Fn::GetAtt:
              - Network
              - Outputs.SubnetIDPrivatec
        MinInstances:
          Ref: MinInstances
        MaxInstances:
          Ref: MaxInstances
