Description: This template creates nginx servers for different environments

Transform: AWS::LanguageExtensions

Parameters:
  NetworkCIDR:
    Description: The CIDR block to share among the environments. It should be a minimum of /19
    Type: String
    AllowedPattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$'

Resources:
  EnvironmentDev:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: example-nested-stacks-environment.yaml
      # TemplateURL: https://devopspro-beyond-2.s3.eu-west-1.amazonaws.com/cloudformation/templates/example-nested-stacks-environment.yaml
      Parameters:
        Name: dev
        NetworkCIDR:
          Fn::Select:
          - 0
          - Fn::Cidr:
            - Ref: NetworkCIDR
            - 2
            - 12
  EnvironmentProd:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://devopspro-beyond-2.s3.eu-west-1.amazonaws.com/cloudformation/templates/example-nested-stacks-environment.yaml
      Parameters:
        Name: prod
        NetworkCIDR:
          Fn::Select:
          - 1
          - Fn::Cidr:
            - Ref: NetworkCIDR
            - 2
            - 12
        MinInstances: 2
        MaxInstances: 5
