Description: This template creates docker servers for different environments

Transform: AWS::LanguageExtensions

Parameters:
  S3Bucket:
    Description: The name of the S3 bucket containing deployment revisions
    Type: String

  NetworkCIDR:
    Description: The CIDR block to share among the environments. It should be a minimum of /19
    Type: String
    AllowedPattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$'

Resources:
  CodeDeployServiceRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://devopspro-beyond-2.s3.eu-west-1.amazonaws.com/chapter9/create-a-codepipeline-pipeline-using-a-git-repository-codebuild-and-codeploy/infra/nested-stacks-codedeploy-roles.yaml
      Parameters:
        S3Bucket:
          Ref: S3Bucket

  CodePipelineServiceRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://devopspro-beyond-2.s3.eu-west-1.amazonaws.com/chapter9/create-a-codepipeline-pipeline-using-a-git-repository-codebuild-and-codeploy/infra/nested-stacks-codepipeline-role.yaml
      Parameters:
        S3Bucket:
          Ref: S3Bucket

  EnvironmentDev:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://devopspro-beyond-2.s3.eu-west-1.amazonaws.com/chapter9/create-a-codepipeline-pipeline-using-a-git-repository-codebuild-and-codeploy/infra/nested-stacks-environment.yaml
      Parameters:
        Name: dev
        NetworkCIDR:
          Fn::Select:
          - 0
          - Fn::Cidr:
            - Ref: NetworkCIDR
            - 2
            - 12
        InstanceProfileArn:
          Fn::GetAtt:
          - CodeDeployServiceRoles
          - Outputs.EC2InstanceProfileArn

  EnvironmentProd:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://devopspro-beyond-2.s3.eu-west-1.amazonaws.com/chapter9/create-a-codepipeline-pipeline-using-a-git-repository-codebuild-and-codeploy/infra/nested-stacks-environment.yaml
      Parameters:
        Name: prod
        NetworkCIDR:
          Fn::Select:
          - 1
          - Fn::Cidr:
            - Ref: NetworkCIDR
            - 2
            - 12
        InstanceProfileArn:
          Fn::GetAtt:
          - CodeDeployServiceRoles
          - Outputs.EC2InstanceProfileArn
        MinInstances: 2
        MaxInstances: 5

Outputs:
  CodeDeployServiceRole:
    Description: The ARN of the CodeDeploy service role
    Value:
      Fn::GetAtt:
      - CodeDeployServiceRoles
      - Outputs.ServiceRoleArn
  CodePipelineServiceRole:
    Description: The ARN of the CodePipeline service role
    Value:
      Fn::GetAtt:
      - CodePipelineServiceRole
      - Outputs.ServiceRoleArn
  DevUrl:
    Description: The url that can be used to reach the load balancer for the dev environment
    Value:
      Fn::GetAtt:
      - EnvironmentDev
      - Outputs.Url
  ProdUrl:
    Description: The url that can be used to reach the load balancer for the prod environment
    Value:
      Fn::GetAtt:
      - EnvironmentProd
      - Outputs.Url
  DevDockerAsg:
    Description: The name of the autoscaling group for docker on dev
    Value:
      Fn::GetAtt:
      - EnvironmentDev
      - Outputs.DockerAsg
  ProdDockerAsg:
    Description: The name of the autoscaling group for docker on prod
    Value:
      Fn::GetAtt:
      - EnvironmentProd
      - Outputs.DockerAsg
